# https://rust-lang.github.io/rustfmt/
edition = "2024"
newline_style = "Unix"
max_width = 100
use_field_init_shorthand = true
force_explicit_abi = true

# Nightly features (uncomment if using nightly)
# unstable_features = true
# imports_granularity = "Crate"
# wrap_comments = true
# comment_width = 80
# format_code_in_doc_comments = true
